name: "🪄 Enhancement"
description: Create a new ticket for requesting an enhancement
title: "🪄 Enhancement - <title>"
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the enhancement
      placeholder: Describe in a few lines your enhancement request
    validations:
      required: true
